version: '3'
services:
  sonar:
    image: sonarqube:7.9-community
    container_name: sonar
    volumes:
      - /opt/sonarqube/extensions:/opt/sonarqube/extensions
      - /opt/sonarqube/logs:/opt/sonarqube/logs
      - /opt/sonarqube/data:/opt/sonarqube/data
      - /opt/sonarqube/conf:/opt/sonarqube/conf
    ports:
      - 9000:9000
    environment:
      SONARQUBE_JDBC_USERNAME: root
      SONARQUBE_JDBC_PASSWORD: root
      SONARQUBE_JDBC_URL: jdbc:postgresql://10.16.105.194:5432/sonar
