version: '3'
services:
  sonar:
    image: sonarqube:7.9-community
    container_name: sonar
    volumes:
      - ./extensions:/opt/sonarqube/extensions
      - ./logs:/opt/sonarqube/logs
      - ./data:/opt/sonarqube/data
      - ./conf:/opt/sonarqube/conf
    ports:
      - 9000:9000
    environment:
      SONARQUBE_JDBC_USERNAME: root
      SONARQUBE_JDBC_PASSWORD: root
      SONARQUBE_JDBC_URL: jdbc:postgresql://127.0.0.1:5432/sonar
