version: '3'
services:
  #nginx容器
  nginx:
    #是否跟随docker启动
    restart: always
    #容器名称
    container_name: aiot-nginx
    #镜像
    image: nginx:alpine
    #映射端口
    ports:
      - "80:80"
      - "443:443"
    #挂载目录
    volumes:
      - ./certs:/certs
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./log:/var/log/nginx
