version: '3'
services:
  mysql-master:
    image: IMAGE_REPOSITORY:IMAGE_VERSION
    hostname: mysql-master
    ports:
    - 3306:3306
    restart: always
    environment:
    - MYSQL_ROOT_HOST= REPLACE_HOST
    - MYSQL_ROOT_PASSWORD= REPLACE_PASSWORD
    - TZ=Asia/Shanghai
    volumes:
    - ./mysql-master/data:/var/lib/mysql
    - ./mysql-master/logs:/var/log/mysql/
    - ./mysql-master/init.d:/docker-entrypoint-initdb.d/:ro
    - ./mysql-master/config:/etc/mysql/conf.d/:rw
    command:
    - "--server-id=1"
    - "--default-authentication-plugin=mysql_native_password"
    - "--character-set-server=utf8mb4"
    - "--max_connections=16384"
    - "--collation-server=utf8mb4_general_ci"
    - "--explicit_defaults_for_timestamp=true"
    - "--lower_case_table_names=1"
    - "--binlog-ignore-db=mysql"
    - "--binlog_format=row"
    - "--log-bin=mysql-bin"
    - "--sync_binlog=1"
    - "--expire_logs_days=7"
    - "--slave_skip_errors=1062"
    - "--sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    networks:
    - edge-gateway-work
    deploy:
      placement:
        constraints:
        - node.hostname == dockerMaster
        - node.role == manager
  mysql-slave:
    image: IMAGE_REPOSITORY:IMAGE_VERSION
    hostname: mysql-slave
    restart: always
    environment:
    - MYSQL_ROOT_HOST= REPLACE_HOST
    - MYSQL_ROOT_PASSWORD= REPLACE_PASSWORD
    - TZ=Asia/Shanghai
    volumes:
    - ./mysql-slave/data:/var/lib/mysql
    - ./mysql-slave/logs:/var/log/mysql/
    - ./mysql-slave/init.d:/docker-entrypoint-initdb.d/:ro
    - ./mysql-slave/config:/etc/mysql/conf.d/:rw
    command:
    - "--server-id=2"
    - "--default-authentication-plugin=mysql_native_password"
    - "--character-set-server=utf8mb4"
    - "--max_connections=16384"
    - "--collation-server=utf8mb4_general_ci"
    - "--explicit_defaults_for_timestamp=true"
    - "--lower_case_table_names=1"
    - "--binlog-ignore-db=mysql"
    - "--binlog_format=row"
    - "--log-bin=mysql-bin"
    - "--sync_binlog=1"
    - "--expire_logs_days=7"
    - "--slave_skip_errors=1062"
    - "--sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    depends_on:
    - mysql-master
    networks:
    - edge-gateway-work
networks:
  edge-gateway-work:
    driver: overlay
    external: true


