version: '3'
services:
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    restart: always
    container_name: kafka
    volumes:
        - /etc/localtime:/etc/localtime
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.16.105.194
      KAFKA_ZOOKEEPER_CONNECT: 10.16.105.194:2181
      KAFKA_ADVERTISED_PORT: 9092
