version: "3"
services:
    redis:
        image: redis:alpine
        container_name: redis-single
        restart: always
        ports:
          - "6379:6379"
        volumes:
          - ./conf:/etc/redis/conf:rw
          - ./data:/data:rw
        command:
          # 执行的命令
          redis-server /etc/redis/conf/redis.conf --appendonly yes
          
