version: "3"
services:
  redis-0:
    image: redis:alpine
    container_name: redis-0
    hostname: redis-0
    restart: always
    volumes:
      - ./node-0/data:/data:rw
      - ./node-0/conf:/conf:rw
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--masterauth PASSWORD"
      - "--daemonize no"
      - "--cluster-enabled yes"
      - "--cluster-config-file /conf/nodes.conf"
      - "--cluster-announce-ip HOST_MACHINE_IP"
      - "--cluster-announce-port 7000"
      - "--cluster-announce-bus-port 17000"
    ports:
      - "7000:6379"
      - "17000:16379"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - edge-gateway-work
  redis-1:
    image: redis:alpine
    container_name: redis-1
    hostname: redis-1
    restart: always
    volumes:
      - ./node-1/data:/data:rw
      - ./node-1/conf:/conf:rw
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--masterauth PASSWORD"
      - "--daemonize no"
      - "--cluster-enabled yes"
      - "--cluster-config-file /conf/nodes.conf"
      - "--cluster-announce-ip HOST_MACHINE_IP"
      - "--cluster-announce-port 7001"
      - "--cluster-announce-bus-port 17001"
    ports:
      - "7001:6379"
      - "17001:16379"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - edge-gateway-work
  redis-2:
    image: redis:alpine
    container_name: redis-2
    hostname: redis-2
    restart: always
    volumes:
      - ./node-2/data:/data:rw
      - ./node-2/conf:/conf:rw
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--masterauth PASSWORD"
      - "--daemonize no"
      - "--cluster-enabled yes"
      - "--cluster-config-file /conf/nodes.conf"
      - "--cluster-announce-ip HOST_MACHINE_IP"
      - "--cluster-announce-port 7002"
      - "--cluster-announce-bus-port 17002"
    ports:
      - "7002:6379"
      - "17002:16379"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - edge-gateway-work
  redis-3:
    image: redis:alpine
    container_name: redis-3
    hostname: redis-3
    restart: always
    volumes:
      - ./node-3/data:/data:rw
      - ./node-3/conf:/conf:rw
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--masterauth PASSWORD"
      - "--daemonize no"
      - "--cluster-enabled yes"
      - "--cluster-config-file /conf/nodes.conf"
      - "--cluster-announce-ip HOST_MACHINE_IP"
      - "--cluster-announce-port 7003"
      - "--cluster-announce-bus-port 17003"
    ports:
      - "7003:6379"
      - "17003:16379"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - edge-gateway-work
  redis-4:
    image: redis:alpine
    container_name: redis-4
    hostname: redis-4
    restart: always
    volumes:
      - ./node-4/data:/data:rw
      - ./node-4/conf:/conf:rw
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--masterauth PASSWORD"
      - "--daemonize no"
      - "--cluster-enabled yes"
      - "--cluster-config-file /conf/nodes.conf"
      - "--cluster-announce-ip HOST_MACHINE_IP"
      - "--cluster-announce-port 7004"
      - "--cluster-announce-bus-port 17004"
    ports:
      - "7004:6379"
      - "17004:16379"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - edge-gateway-work
  redis-5:
    image: redis:alpine
    container_name: redis-5
    hostname: redis-5
    restart: always
    volumes:
      - ./node-5/data:/data:rw
      - ./node-5/conf:/conf:rw
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--masterauth PASSWORD"
      - "--daemonize no"
      - "--cluster-enabled yes"
      - "--cluster-config-file /conf/nodes.conf"
      - "--cluster-announce-ip HOST_MACHINE_IP"
      - "--cluster-announce-port 7005"
      - "--cluster-announce-bus-port 17005"
    ports:
      - "7005:6379"
      - "17005:16379"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - edge-gateway-work
networks:
  edge-gateway-work:
    driver: bridge
